# Generated by Django 4.2.29 on 2026-03-12 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resena',
            name='garaje',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='api.garaje'),
            preserve_default=False,
        ),
    ]
