# Generated by Django 4.2.29 on 2026-03-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_usuario_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotogaraje',
            name='id_imagen',
        ),
        migrations.AddField(
            model_name='fotogaraje',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fotogaraje',
            name='imagen',
            field=models.ImageField(default='', upload_to='garajes/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
