# Generated by Django 4.2.29 on 2026-03-18 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_pago_monto_total_remove_usuario_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('NUEVA_RESERVA', 'Nueva solicitud de reserva'), ('RESERVA_ACEPTADA', 'Tu reserva ha sido aceptada'), ('RESERVA_RECHAZADA', 'Tu reserva ha sido rechazada'), ('MENSAJE_CHAT', 'Tienes un nuevo mensaje')], max_length=20)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_reserva', to='api.reserva')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='api.usuario')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
