name: Deploy tuplaza Frontend & Backend

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar el código del repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Login a Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # =========================
      # FRONTEND (Angular)
      # =========================

      - name: Build Frontend Docker image
        run: |
          docker build \
            -t tuplaza-frontend \
            -f deployment/frontend/Dockerfile .

      - name: Push Frontend Docker image
        run: |
          docker tag tuplaza-frontend ${{ secrets.DOCKER_USERNAME }}/tuplaza-frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/tuplaza-frontend:latest

      # =========================
      # BACKEND (PHP)
      # =========================

      - name: Build Backend Docker image
        run: |
          docker build \
            -t tuplaza-backend \
            -f deployment/backend/Dockerfile .

      - name: Push Backend Docker image
        run: |
          docker tag tuplaza-backend ${{ secrets.DOCKER_USERNAME }}/tuplaza-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/tuplaza-backend:latest

      # =========================
      # DEPLOY EN SERVIDOR
      # =========================

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # NETWORK DOCKER
            docker network create tuplaza-network || true

            # LEVANTAR BASE DE DATOS PRODUCCION
            cd /home/tuplaza/proyecto/TuPlaza/mysql-prod
            docker compose up -d

            # FRONTEND
            docker pull ${{ secrets.DOCKER_USERNAME }}/tuplaza-frontend:latest
            docker stop tuplaza-frontend || true
            docker rm tuplaza-frontend || true
            docker run -d \
              --restart unless-stopped \
              --network tuplaza-network \
              -p 8080:80 \
              --name tuplaza-frontend \
              ${{ secrets.DOCKER_USERNAME }}/tuplaza-frontend:latest

            # BACKEND
            docker pull ${{ secrets.DOCKER_USERNAME }}/tuplaza-backend:latest
            docker stop tuplaza-backend || true
            docker rm tuplaza-backend || true
            docker run -d \
              --restart unless-stopped \
              --env-file /home/tuplaza/proyecto/TuPlaza/laravel-config/.env \
              --network tuplaza-network \
              -p 8081:80 \
              --name tuplaza-backend \
              ${{ secrets.DOCKER_USERNAME }}/tuplaza-backend:latest
